//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoLi.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoLi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lists ähnelt.
        /// </summary>
        public static string LISTS_TITLE {
            get {
                return ResourceManager.GetString("LISTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string MAIN_MENU_EDIT {
            get {
                return ResourceManager.GetString("MAIN_MENU_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string MAIN_MENU_FILE {
            get {
                return ResourceManager.GetString("MAIN_MENU_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string MAIN_MENU_SETTINGS {
            get {
                return ResourceManager.GetString("MAIN_MENU_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New List ähnelt.
        /// </summary>
        public static string MENU_EDIT_LISTS_ADD {
            get {
                return ResourceManager.GetString("MENU_EDIT_LISTS_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete List ähnelt.
        /// </summary>
        public static string MENU_EDIT_LISTS_DELETE {
            get {
                return ResourceManager.GetString("MENU_EDIT_LISTS_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename List ähnelt.
        /// </summary>
        public static string MENU_EDIT_LISTS_RENAME {
            get {
                return ResourceManager.GetString("MENU_EDIT_LISTS_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tasks ähnelt.
        /// </summary>
        public static string MENU_EDIT_TASKS {
            get {
                return ResourceManager.GetString("MENU_EDIT_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Task ähnelt.
        /// </summary>
        public static string MENU_EDIT_TASKS_ADD {
            get {
                return ResourceManager.GetString("MENU_EDIT_TASKS_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Task ähnelt.
        /// </summary>
        public static string MENU_EDIT_TASKS_DELETE {
            get {
                return ResourceManager.GetString("MENU_EDIT_TASKS_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Task ähnelt.
        /// </summary>
        public static string MENU_EDIT_TASKS_EDIT {
            get {
                return ResourceManager.GetString("MENU_EDIT_TASKS_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string MENU_FILE_CLOSE {
            get {
                return ResourceManager.GetString("MENU_FILE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string MENU_FILE_SAVE {
            get {
                return ResourceManager.GetString("MENU_FILE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string MENU_SETTINGS_LANGUAGE {
            get {
                return ResourceManager.GetString("MENU_SETTINGS_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        public static string MENU_SETTINGS_LANGUAGE_DE {
            get {
                return ResourceManager.GetString("MENU_SETTINGS_LANGUAGE_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string MENU_SETTINGS_LANGUAGE_EN {
            get {
                return ResourceManager.GetString("MENU_SETTINGS_LANGUAGE_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your entry contains invalid characters. ähnelt.
        /// </summary>
        public static string MESSAGE_BOX_ERROR_INVALID_CHARACTERS {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_ERROR_INVALID_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changes were saved successfully ähnelt.
        /// </summary>
        public static string MESSAGEBOX_CHANGES_SUCCESFULLY_SAVED {
            get {
                return ResourceManager.GetString("MESSAGEBOX_CHANGES_SUCCESFULLY_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully saved ähnelt.
        /// </summary>
        public static string MESSAGEBOX_CHANGES_SUCCESFULLY_SAVED_TITLE {
            get {
                return ResourceManager.GetString("MESSAGEBOX_CHANGES_SUCCESFULLY_SAVED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not all required fields have been filled. ähnelt.
        /// </summary>
        public static string MESSAGEBOX_ERROR_MISSING_INPUT {
            get {
                return ResourceManager.GetString("MESSAGEBOX_ERROR_MISSING_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string MESSAGEBOX_ERROR_TITLE {
            get {
                return ResourceManager.GetString("MESSAGEBOX_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are unsaved changes to the list. Do you want to save the changes? ähnelt.
        /// </summary>
        public static string MESSAGEBOX_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("MESSAGEBOX_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Changes? ähnelt.
        /// </summary>
        public static string MESSAGEBOX_SAVE_CHANGES_TITLE {
            get {
                return ResourceManager.GetString("MESSAGEBOX_SAVE_CHANGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tasks ähnelt.
        /// </summary>
        public static string TASKS_TITLE {
            get {
                return ResourceManager.GetString("TASKS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The list name is already taken. Please choose another name. ähnelt.
        /// </summary>
        public static string WINDOW_MAIN_ERROR_LIST_EXISTS_ALREADY {
            get {
                return ResourceManager.GetString("WINDOW_MAIN_ERROR_LIST_EXISTS_ALREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error occurred while adding the task. Please try again. ähnelt.
        /// </summary>
        public static string WINDOW_MAIN_NEW_TASK_EXCEPTION {
            get {
                return ResourceManager.GetString("WINDOW_MAIN_NEW_TASK_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set name ähnelt.
        /// </summary>
        public static string WINDOW_NEWLISTDIALOG_BUTTON_SET {
            get {
                return ResourceManager.GetString("WINDOW_NEWLISTDIALOG_BUTTON_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert a name for your list ähnelt.
        /// </summary>
        public static string WINDOW_NEWLISTDIALOG_LABEL {
            get {
                return ResourceManager.GetString("WINDOW_NEWLISTDIALOG_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set list name ähnelt.
        /// </summary>
        public static string WINDOW_NEWLISTDIALOG_TITLE {
            get {
                return ResourceManager.GetString("WINDOW_NEWLISTDIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string WINDOW_TASKEDITOR_LABEL_TASK_DESCRIPTION {
            get {
                return ResourceManager.GetString("WINDOW_TASKEDITOR_LABEL_TASK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string WINDOW_TASKEDITOR_LABEL_TASK_TITLE {
            get {
                return ResourceManager.GetString("WINDOW_TASKEDITOR_LABEL_TASK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task Editor ähnelt.
        /// </summary>
        public static string WINDOW_TASKEDITOR_TITLE {
            get {
                return ResourceManager.GetString("WINDOW_TASKEDITOR_TITLE", resourceCulture);
            }
        }
    }
}
